spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

#아티스트 Pagination 설정
  data:
    web:
      pageable:
        one-indexed-parameters: true  #페이지 인덱스 1부터 시작

  profiles:
    include:
      - cors
      - secret


