spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
#    show-sql: true

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  profiles:
    include:
      - cors
      - secret

server:
  port: 8081