spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  #    show-sql: true

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  profiles:
    include:
      - cors
      - secret


  refesta:
    front:
      url: https://j10a601.p.ssafy.io
#      http://localhost:5173
#      https://j10a601.p.ssafy.io
#    https://localhost:5173
    back:
      url: https://j10a601.p.ssafy.io
#      http://localhost:8080
#      https://j10a601.p.ssafy.io
#    https://localhost:8080
    recommend:
      url: https://j10a601.p.ssafy.io
#      http://localhost:5000
#      https://j10a601.p.ssafy.io


server:
  port: 8081